### ISSUE TITLE
POST not allowed on conducto.com/program/program

### ISSUE THREAD

**Issue by MatrixManAtYrService** [conducto/conducto#3] opened 2020-05-31 00:11 UTC
My guess is that is more relevant to the web service, but I'm not sure where that repo lives.  I think that this snippet (edited slightly) tells the whole story:  

    ❯ python demo.py islands --local

        Traceback (most recent call last):
          .../conducto/api/api_utils.py", line 76, in get_data

        Code: MethodNotAllowed
        Message: The specified method is not allowed against this resource.
        status_code=405
        url=https://conducto.com/program/program

`demo.py` was freshly cloned from: https://github.com/conducto/demo

This was working for me yesterday, which makes me think that its resolution is out of my hands.  I'd love to be wrong about that though, can you tell me where I'm going wrong?

**Comment by mjachowski** [comment] 2020-05-31 00:26
I'll take a look. Can you first confirm that you are seeing this on the latest version of conducto? Just do `pip install --upgrade conducto`.

**Comment by MatrixManAtYrService** [comment] 2020-05-31 00:30
I believe that I am:

> Successfully installed conducto-0.0.55

When I noticed that 0.0.55 came out less than a day ago I tried downgrading to 0.0.54 and 0.0.53, but I get the same error for all three versions.

**Comment by mjachowski** [comment] 2020-05-31 00:31
Yep, that's the latest. I cannot reproduce this issue, but I'm poking around in hopes of seeing something...

**Comment by mjachowski** [comment] 2020-05-31 00:35
If you have the time, any chance you could jump on our slack channel? Might help to more quickly diagnose this problem.

**Comment by mjachowski** [comment] 2020-05-31 00:35
https://join.slack.com/t/conductohq/shared_invite/zt-co82g0up-5HiC6lptzhnhgyPGmKvA3Q

**Comment by mjachowski** [comment] 2020-05-31 01:57
Ok, this is fixed now. We had an issue with of redirect of conducto.com -> www.conducto.com that is now resolved. Thanks for reporting the issue!

**Closed as completed by mjachowski** 2020-05-31 01:57 UTC
